import type { Metadata } from "next";
import ScrollToTop from "@/components/ScrollToTop";
import Resume from "@/components/sections/Resume";
import About from "@/components/sections/About";
import Skills from "@/components/sections/Skills";
import Experience from "@/components/sections/Experience";
import EducationSection from "@/components/sections/Education";
import Projects from "@/components/sections/Project";
import Blog from "@/components/sections/Blog";
import Contact from "@/components/sections/Contact";
import Footer from "@/components/sections/Footer";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        {children}

        <ScrollToTop />
        <Resume />
        <About />
        <Skills />
        <Experience />
        <EducationSection />
        <Projects />
        <Contact />
        <Blog />
        <Footer />
      </body>
    </html>
  );
}
